name: Beta Push
concurrency:
  group: betapush
on:
  push:
    branches:
      - beta
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          YARN_NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          YARN_NPM_PUBLISH_REGISTRY: https://npm.pkg.github.com/techform
        run: yarn release
